vich_uploader:
    db_driver: orm

    mappings:
        profil_directory:
            uri_prefix:         '%profil_images%'
            upload_destination: '%kernel.project_dir%/public%profil_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer